import { useEffect, useState } from 'react'
import api from '../services/api'
import { Link } from 'react-router-dom'

const STATUS_LABELS = { pending: 'Waiting for arrival', approved: 'Waiting for arrival', ordered: 'Waiting for arrival', received: 'Delivered' }

export default function ManagerDashboard() {
  const [summary, setSummary] = useState(null)
  const [reorders, setReorders] = useState([])
  const [notifications, setNotifications] = useState([])
  const [error, setError] = useState(null)
  useEffect(() => { Promise.all([api.get('/api/v1/dashboard'), api.get('/api/v1/reorder'), api.get('/api/v1/notifications')]).then(([dashboard, requests, managerNotifications]) => { setSummary(dashboard); setReorders(requests); setNotifications(managerNotifications) }).catch((err) => setError(err.message)) }, [])
  const low = summary?.summary?.low_stock || 0
  const out = summary?.summary?.out_of_stock || 0
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Manager control room</p><h1>All outlet operations</h1><p>One view across inventory health, loyalty, and purchasing decisions.</p></div><Link className="primary-button" to="/reorder">Review reorders</Link></div>{error && <p className="alert" role="alert">{error}</p>}<section className="manager-metrics"><div className="metric-card"><span>Total inventory items</span><strong>{summary?.summary?.total ?? '—'}</strong><small>Across every outlet</small></div><div className="metric-card"><span>Low stock</span><strong className="gold-text">{low}</strong><small>Needs purchasing review</small></div><div className="metric-card"><span>Out of stock</span><strong className="red-text">{out}</strong><small>Immediate attention</small></div><div className="metric-card"><span>Active reorders</span><strong>{reorders.filter((item) => item.status !== 'received').length}</strong><small>Awaiting delivery</small></div></section><section className="manager-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Inventory</p><h2>Manager summary</h2></div><Link className="text-link" to="/inventory">Open inventory</Link></div><div className="manager-summary"><div><strong>{summary?.summary?.in_stock ?? '—'}</strong><span>In stock</span></div><div><strong>{low}</strong><span>Low stock</span></div><div><strong>{out}</strong><span>Out of stock</span></div></div></div><div className="panel attention-panel"><p className="eyebrow">Action queue</p><h2>Purchasing attention</h2>{reorders.slice(0, 4).map((request) => <div className="queue-row" key={request.id}><span>{request.inventory_item_name || request.inventory_item_id}{request.outlet ? ` (${request.outlet})` : ''}</span><span className={`status-badge status-${request.status === 'received' ? 'good' : 'low'}`}>{STATUS_LABELS[request.status] || request.status}</span></div>)}{!reorders.length && <p className="muted">No reorder requests yet.</p>}</div></section><section className="panel notification-panel"><div className="panel-heading"><div><p className="eyebrow">Manager notifications</p><h2>What needs attention</h2></div><span className="muted">{notifications.length} alerts</span></div>{notifications.slice(0, 8).map((notification) => <div className="queue-row" key={notification.id}><span>{notification.message}</span><span className={`status-badge ${notification.kind === 'inventory' ? 'status-out' : 'status-good'}`}>{notification.kind}</span></div>)}{!notifications.length && <p className="muted">No notifications.</p>}</section></div>
}
